quoter_selection=(
    "Intelligence is the ability to avoid doing work, yet getting the work done.\n - Linus Torvalds"
    "People who are doing things for fun do things the right way by themselves.\n - Linus Torvalds"
    "Talk is cheap. Show me the code.\n - Linus Torvalds"
    "Those that can, do. Those that can't, complain.\n - Linus Torvalds"
    "Things that are impossible just take longer.\n - Ian Hickson"
    "When in doubt, leave it out.\n - Joshua Bloch"
    "In theory, theory and practice are the same. In practice, they’re not.\n - Yoggi Berra"
    "I don't care if it works on your machine! We are not shipping your machine!\n - Vidiu Platon"
    "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.\n - Martin Golding"
    "First, solve the problem. Then, write the code.\n - John Johnson"
    "Copy and paste is a design error.\n - David Parnas"
    "Testing shows the presence, not the absence of bugs.\n - Edsger W. Dijkstra"
    "I would love to change the world, but they won't give me the source code.\n - Anonymous"
    "Computers are like bikinis. They save people a lot of guesswork.\n - Sam Ewing"
    "Never trust a computer you can’t throw out a window.\n - Steve Wozniak"
)
